version: '3.9'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: navigator_diary
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/navigator_diary?schema=public
      PORT: 3000
      JWT_SECRET: change_me
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  pgdata:
